version: "3.9"
services:
  api:
    build: .
    container_name: api_kazanto
    command: python main.py
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - padrao
  database:
    image: controle_financeiro_db
    container_name: database
    networks:
      - padrao
    ports:
      - 3306:3306

networks:
  padrao:
    driver: bridge
